ユーザーが参加したイベントの情報を返すAPI
dorayaki-do/dorayaki-do pull request #22
Opened 2021-09-14 12:22 UTC by segatomo

- ユーザーが参加したイベントの緯度と経度を返す
- 確認方法
  - `$ curl -X GET localhost:8080/users/me/events`

2021-09-14 13:58 UTC, Hamumayo55 requested changes
一箇所コメントしました！

2021-09-14 13:58 UTC, Hamumayo55 commented on server/pkg/controllers/user_controller.go
> +      		Eventname:    content.Eventname,
Bookテーブルの`Eventname `カラムは削除したので、ここも削除お願いします

2021-09-14 14:02 UTC, segatomo commented on server/pkg/controllers/user_controller.go
> +      		Eventname:    content.Eventname,
削除しました！

2021-09-14 14:04 UTC, Hamumayo55 approved these changes

2021-09-14 14:04 UTC, Hamumayo55 commented
LGTM!

2021-09-14 14:24 UTC, disVill commented on server/pkg/controllers/user_controller.go
> +	session.Set("UserID", 1)
session.Set("user", nickname)

2021-09-15 02:18 UTC, segatomo commented
- レスポンスにeventid等を追加
- イベントの重複を無くした

2021-09-15 04:29 UTC, merged